default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ernane
  password: ernane
  host: localhost

development:
  <<: *default
  database: chat_app_development

test:
  <<: *default
  database: chat_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: chat_app_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: your_postgres_host